### PR TITLE
Add ... to join and similarity calculation functions

### PR DESCRIPTION
**Pull request by jorainer**
This is to fix issue https://github.com/rformassspectrometry/Spectra/issues/131

### CODE REVIEW

**Comment by lgatto** [comment]
@jorainer - can you also push to Bioconductor, or do you want me to do it?

**Comment by jorainer** [comment]
Can you please push to BioC?

**Comment by lgatto** [comment]
Done - could you confirm that you have write access.

**Comment by jorainer** [comment]
I think I don't need write access to the `MsCoreUtils` BioC repo (although I think I have) - it's enough if you and Sebastian can push there.

**Pull request merged**
