### PR TITLE
feat Random Forest imputation

### PR DESCRIPTION
**Pull request by cvanderaa**
Hi, 

I would like to provide a solution to an old issue (https://github.com/rformassspectrometry/MsCoreUtils/issues/82). In this PR, I created an interface to `missForest` to perform Random Forest imputation. I didn't modify the unit tests as I saw it automatically checks all the imputation methods. I adapted the documentation. 

I also adapted the NEWS file and did a version bump, although I am now wondering whether that was a good idea. Let me know if I should revert the last commit.

### CODE REVIEW

**Comment by cvanderaa** [comment]
Never mind the last comment. I didn't realize I was behind the master and had to solve some conflicts locally. I did update the NEWS.md, but I **did not** bump the version. Let me know if I should do it.

**Comment by cvanderaa** [comment]
The checks fail with error: 

```
Error in `preprocessCore::normalize.quantiles(x, ...)`: ERROR; return code from pthread_create() is 22
```

I remember QFeatures had the same issue and was fixed by Laurent as discussed in [this issue](https://github.com/Bioconductor/bioconductor_docker/issues/22).

**Comment by lgatto** [comment]
Could you also bump the version to 1.9.1

**Comment by cvanderaa** [comment]
Done. I also skipped the manual install of `preprocessCore` for windows as it leads to error.

**Pull request merged**
