### PR TITLE
Implement peak joining functions in C

### PR DESCRIPTION
**Pull request by jorainer**
While the `join*` functions are very elegantly implemented by @sgibb in R, the matching between peaks is still the biggest bottleneck in spectrum comparison.

This PR adds an implementation of the outer join in C:

```r
library(MsCoreUtils)
library(microbenchmark)
x <- as.numeric(c(1, 2, 5, 6))
y <- as.numeric(2:5)
microbenchmark(
    MsCoreUtils:::.joinOuter(x, y, 0, 0),
    MsCoreUtils:::.cjoinOuter(x, y, 0, 0)
)
Unit: microseconds
                                  expr   min     lq    mean median     uq   max
  MsCoreUtils:::.joinOuter(x, y, 0, 0) 108.5 110.65 127.316 111.95 119.55 221.2
 MsCoreUtils:::.cjoinOuter(x, y, 0, 0)  17.7  18.50  21.936  20.10  21.45 103.5
 neval cld
   100   b
   100  a 
```

I did also a lot of comparison (also on a data set of ~ 500,000 real spectra) to check that both functions yield the same result. They are always identical with the exception that the original implementation has a problem with ties, i.e. if in one of the vectors values are duplicated:

```r
a <- c(1, 2, 4, 4, 5)
b <- c(2, 3, 4, 5, 6)
MsCoreUtils:::.joinOuter(a, b, 0, 0)
$x
[1]  1  2 NA NA  4  5 NA

$y
[1] NA  1  2 NA  3  4  5

MsCoreUtils:::.cjoinOuter(a, b, 0, 0)
$x
[1]  1  2 NA  3  4  5 NA

$y
[1] NA  1  2  3 NA  4  5

```

The original implementation drops/skips element `3` from `a` entirely while the new implementation reports the first mapping.

Happy to discuss if this is worth the effort - and even more happy if someone can come up with a more elegant (and faster) implementation in C!

If we agree I would also implement the other join operations in C and change `join` to use the C functions.

### CODE REVIEW

**Comment by jorainer** [comment]
Note: I will add more unit tests and try to simplify the C code. So, no need to review right now. I will ask for review once I feel it's *stable* enough.

**Comment by jorainer** [comment]
I simplified the outer join implementation. @sgibb, once you're OK with the outer join and left join C implementation I would make them the default for the `join` function (and also use them for the right and the inner join).

**Comment by jorainer** [comment]
@sgibb, should I close this issue, compare the performance using your new `closest` C implementation and open it again if it still makes sense to add?

**Comment by sgibb** [comment]
I had the same question. I am wondering whether it is worth the hassle to rewrite this in C.
On my local branch I additionally removed the `match.arg` from `join`:
```git
diff --git a/R/matching.R b/R/matching.R
index 0689715..cfd43d7 100644
--- a/R/matching.R
+++ b/R/matching.R
@@ -243,7 +243,7 @@ common <- function(x, table, tolerance = Inf, ppm = 0,
 join <- function(x, y, tolerance = 0, ppm = 0,
                  type = c("outer", "left", "right", "inner"), .check = TRUE,
                  ...) {
-    switch(match.arg(type),
+    switch(type,
            "outer" = .cjoinOuter(
                x, y, tolerance = tolerance, ppm = ppm, .check = .check
            ),
@@ -255,7 +255,9 @@ join <- function(x, y, tolerance = 0, ppm = 0,
            ),
            "inner" = .joinInner(
                x, y, tolerance = tolerance, ppm = ppm, .check = .check
-           )
+           ),
+           stop("'type' has to be one of \"outer\", \"left\", \"right\", or ",
+                "\"inner\"")
     )
 }
```
With this in place I got the following benchmark results:
``` r
library("MsCoreUtils")
#> 
#> Attaching package: 'MsCoreUtils'
#> The following object is masked from 'package:stats':
#> 
#>     smooth
library("microbenchmark")

set.seed(42)
l <- list(
    small = list(x = as.numeric(c(1, 2, 5, 6)), y = as.numeric(2:5)),
    middle = list(x = sample(1000, 700), y = sample(1000, 700)),
    large = list(x = sample(1e4, 7e3), y = sample(1e4, 7e3))
)

for (i in seq(along=l)) {
    print(microbenchmark(
        rjr=MsCoreUtils:::join(l[[i]]$x, l[[i]]$y, 0, 0, type = "right", .check = FALSE),
        rji=MsCoreUtils:::join(l[[i]]$x, l[[i]]$y, 0, 0, type = "inner", .check = FALSE),
        rjl=MsCoreUtils:::join(l[[i]]$x, l[[i]]$y, 0, 0, type = "left", .check = FALSE),
        cjl=MsCoreUtils:::.cjoinLeft(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        rjo=MsCoreUtils:::join(l[[i]]$x, l[[i]]$y, 0, 0, type = "outer", .check = FALSE),
        cjo=MsCoreUtils:::.cjoinOuter(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        times=1000
    ))
}
#> Unit: microseconds
#>  expr    min      lq     mean  median      uq     max neval  cld
#>   rjr 14.402 15.6775 20.02162 18.4340 22.1960 106.197  1000   c 
#>   rji 15.826 17.4570 22.78831 20.3130 25.0235 208.957  1000    d
#>   rjl 11.278 12.5120 16.10948 15.1495 16.7675  95.984  1000  b  
#>   cjl  9.318 10.5080 14.10449 13.4105 14.7365 227.518  1000 a   
#>   rjo 11.170 12.4755 16.12098 15.1425 16.7620 153.098  1000  b  
#>   cjo  9.365 10.6345 13.93237 13.4415 14.9105  59.139  1000 a   
#> Unit: microseconds
#>  expr    min      lq     mean  median      uq      max neval cld
#>   rjr 26.213 28.6715 35.73511 29.6565 31.7880 3227.904  1000  ab
#>   rji 30.513 33.4575 41.47176 34.5615 37.1020 3164.230  1000   b
#>   rjl 23.108 25.4025 29.09883 26.3865 28.1380  101.156  1000  a 
#>   cjl 21.594 23.9275 27.13698 24.9905 26.4960   71.181  1000  a 
#>   rjo 23.342 24.7755 31.63466 25.4425 27.2640 3189.886  1000  ab
#>   cjo 21.910 23.2515 29.78510 23.8965 25.6235 3076.448  1000  a 
#> Unit: microseconds
#>  expr     min       lq     mean  median       uq      max neval cld
#>   rjr 155.761 161.2145 197.8438 166.599 184.4290 4056.400  1000  b 
#>   rji 182.420 190.0430 229.0445 195.658 217.7980 3824.452  1000   c
#>   rjl 160.742 164.4475 198.5058 169.425 187.5445 2877.967  1000  b 
#>   cjl 158.561 162.4455 200.9524 167.271 184.2315 3525.283  1000  bc
#>   rjo 120.587 126.9200 162.1407 131.154 145.7715 3272.432  1000 a  
#>   cjo 119.320 125.4215 178.2189 129.980 145.6600 3786.950  1000 ab
```

<sup>Created on 2020-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Looking at these numbers I don't think we need to implement the join* methods in C anymore.

But I don't really understand why the `join(..., type = "outer")` is faster than the `join(..., type = "inner")` because the former incorporates the latter and adds sorting etc. on top, so it should be slower. Could you reproduce these results?

**Comment by sgibb** [comment]
Updated benchmark with correct R implementation:
``` r
library("MsCoreUtils")
#> 
#> Attaching package: 'MsCoreUtils'
#> The following object is masked from 'package:stats':
#> 
#>     smooth
library("microbenchmark")

set.seed(42)
l <- list(
    small = list(x = as.numeric(c(1, 2, 5, 6)), y = as.numeric(2:5)),
    middle = list(x = sample(1000, 700), y = sample(1000, 700)),
    large = list(x = sample(1e4, 7e3), y = sample(1e4, 7e3))
)

for (i in seq(along=l)) {
    print(microbenchmark(
        rjr=MsCoreUtils:::.joinRight(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        rji=MsCoreUtils:::.joinInner(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        rjl=MsCoreUtils:::.joinLeft(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        cjl=MsCoreUtils:::.cjoinLeft(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        rjo=MsCoreUtils:::.joinOuter(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        cjo=MsCoreUtils:::.cjoinOuter(l[[i]]$x, l[[i]]$y, 0, 0, .check = FALSE),
        times=1000
    ))
}
#> Unit: microseconds
#>  expr    min      lq     mean  median      uq      max neval cld
#>   rjr 12.345 13.6280 17.40802 16.4415 18.7270   67.009  1000 ab 
#>   rji 13.493 15.0835 19.26565 17.9855 21.0410   82.946  1000  b 
#>   rjl 12.408 13.8410 20.09616 16.7475 19.2435 2157.080  1000  b 
#>   cjl  9.439 10.8565 14.07155 13.0950 15.0250  212.561  1000 a  
#>   rjo 60.356 66.1640 80.14908 78.6265 87.3950  498.320  1000   c
#>   cjo  9.459 10.9060 13.93918 13.0905 15.2900   81.440  1000 a  
#> Unit: microseconds
#>  expr     min       lq      mean   median       uq      max neval cld
#>   rjr  24.920  27.8535  32.29713  29.9390  33.9725   96.308  1000  a 
#>   rji  29.017  32.5430  40.24315  34.9865  38.9120 3162.106  1000  a 
#>   rjl  25.746  28.4970  32.55341  30.2575  34.1065   96.848  1000  a 
#>   cjl  22.573  26.4225  30.04869  28.2060  31.4895  108.826  1000  a 
#>   rjo 265.173 271.0965 297.38946 273.9975 284.9765 3580.113  1000   b
#>   cjo  21.948  23.5910  29.91999  25.0085  27.4130 3199.263  1000  a 
#> Unit: microseconds
#>  expr      min        lq      mean    median       uq        max neval cld
#>   rjr  154.939  161.6515  195.2773  167.6915  186.395   2862.840  1000  a 
#>   rji  181.529  190.2430  245.5238  198.1220  223.549   3572.815  1000  a 
#>   rjl  155.239  161.8055  203.0427  169.6360  191.941   3589.972  1000  a 
#>   cjl  158.953  166.5860  194.8507  172.8970  194.453   2511.891  1000  a 
#>   rjo 2726.680 2836.9185 3070.1063 2914.5240 3040.135   7081.839  1000   b
#>   cjo  118.701  129.5070  307.6483  135.6220  154.564 135844.970  1000  a
```

<sup>Created on 2020-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jorainer** [comment]
OK, but then at least for the outer join I think the c implementation makes sense. For the left join there is no benefit. I will now clean the branch and once done will ask you again for your review @sgibb , is that OK?

**Comment by jorainer** [comment]
OK, I've cleaned-up everything. Please have a look at the PR when you have time @sgibb

**Pull request closed without merging**
